'use client'

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthProvider from "../features/auth/provider/auth-provider";

const bounded = localFont({
  src: [
    {
      path: "./fonts/Bounded-Regular.woff2",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/Bounded-ExtraLight.woff2",
      weight: "300",
      style: "light"
    }
  ],
  variable: "--font-bounded"
});

const hikasami = localFont({
  src: [
    {
      path: "./fonts/Hikasami-Regular.woff2",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/Hikasami-Bold.woff2",
      weight: "700",
      style: "bold"
    },
    {
      path: "./fonts/Hikasami-Medium.woff2",
      weight: "500",
      style: "medium"
    },
    {
      path: "./fonts/Hikasami-SemiBold.woff2",
      weight: "600",
      style: "semibold"
    }
  ],
  variable: "--font-hikasami"
});

const metadata: Metadata = {
  title: "MindBridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hikasami.variable} ${bounded.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
